# Generated by Django 4.1.4 on 2022-12-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_remove_contactsphone_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='logo')),
            ],
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
