# Generated by Django 4.1.4 on 2022-12-22 14:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_homeabout_homeacademy_homeafisha_homebanner_homebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebook',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homebook',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
