# Generated by Django 4.1.4 on 2022-12-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_alter_homebook_description_alter_homebook_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
