# Generated by Django 4.1.4 on 2022-12-23 18:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Text',
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
