# Generated by Django 4.1.4 on 2022-12-23 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0008_remove_news_text_news_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='news')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('file', models.FileField(upload_to='issues')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.issuescategory')),
            ],
        ),
    ]
