# Generated by Django 4.1.4 on 2022-12-23 19:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0009_issuescategory_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
