# Generated by Django 4.1.4 on 2022-12-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0010_issues_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='image',
        ),
        migrations.AddField(
            model_name='homebanner',
            name='home',
            field=models.FileField(blank=True, null=True, upload_to='banner'),
        ),
    ]
